### ISSUE TITLE
Froala's border style in forms diffs from other fields 

### ISSUE THREAD

**Issue by Xotic750** [ProReNata/RichTextEditor#2]
Ref: https://github.com/ProReNata/Byxelkrok/issues/114

**Comment by SergioCrisostomo** [comment]
If we add CSS rules here we need to take into account that Froala is used in Calendar but also in Ottenby as replacement to Redactor. So we need to make 2 CSS profiles and test both when we change things.

**Comment by Xotic750** [comment]
This is now done in Byx
